
services:
  postgres:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: nyc
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

  airflow:
    image: apache/airflow:2.9.3
    container_name: airflow
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://dbuser:dbpass@postgres:5432/nyc
      AIRFLOW__WEBSERVER__SECRET_KEY: supersecret
      _PIP_ADDITIONAL_REQUIREMENTS: "psycopg2-binary dbt-core dbt-postgres pandas pyarrow requests"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./dbt:/opt/airflow/dbt
    command: bash -c "airflow db upgrade && airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com || true && airflow webserver & airflow scheduler"
    ports:
      - "8080:8080"

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase.db

volumes:
  pgdata:
